replicaCount: 3

image:
  repository: dockerha08/beartainer
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80

containerPort: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
