name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/beartainer/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Ensure gh-pages branch exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git ls-remote --exit-code --heads https://github.com/${{ github.repository }} gh-pages || \
          (git clone --depth=1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} temp && \
           cd temp && \
           git checkout --orphan gh-pages && \
           git rm -rf . && \
           echo "apiVersion: v1\nentries: {}" > index.yaml && \
           git add index.yaml && \
           git commit -m "Initialize gh-pages" && \
           git push origin gh-pages)

      - name: Package Helm chart
        run: |
          mkdir -p packaged
          helm package charts/beartainer -d packaged

      - name: Download existing index.yaml
        run: |
          mkdir -p repo
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} repo
          cp repo/index.yaml repo_index.yaml || true

      - name: Fix empty index.yaml if needed
        run: |
          if [ -f repo_index.yaml ] && [ ! -s repo_index.yaml ]; then
            echo "apiVersion: v1
entries: {}" > repo_index.yaml
          fi

      - name: Update Helm repo index
        run: |
          helm repo index packaged --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }} --merge repo_index.yaml

      - name: Push to gh-pages
        run: |
          cp -r packaged/* repo/
          cd repo
          git add .
          git diff --quiet && echo "No changes to commit" || git commit -m "Update Helm chart from GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin gh-pages
