name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/beartainer/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Ensure gh-pages branch exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git ls-remote --exit-code --heads https://github.com/${{ github.repository }} gh-pages; then
            git clone --depth=1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} temp
            cd temp
            git checkout --orphan gh-pages
            git rm -rf .
            echo -e "apiVersion: v1\nentries: {}" > index.yaml
            git add index.yaml
            git commit -m "Initialize gh-pages"
            git push origin gh-pages
          fi

      - name: Package Helm chart
        run: |
          mkdir -p packaged
          helm package charts/beartainer -d packaged

      - name: Clone gh-pages branch
        run: |
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} repo

      - name: Prepare repo_index.yaml
        run: |
          if [ ! -s repo/index.yaml ] || ! grep -q 'apiVersion:' repo/index.yaml; then
            echo -e "apiVersion: v1\nentries: {}" > repo/index.yaml
          fi
          cp repo/index.yaml repo_index.yaml

      - name: Update Helm repo index
        run: |
          helm repo index packaged --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }} --merge repo_index.yaml

      - name: Commit and push to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp -r packaged/* repo/
          cp packaged/index.yaml repo/index.yaml
          cd repo
          git add .
          if ! git diff --quiet; then
            git commit -m "Update Helm chart from GitHub Actions"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin gh-pages
          else
            echo "No changes to commit."
          fi
